# Generated by Django 4.0.1 on 2022-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_features_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
