# Generated by Django 4.0.1 on 2022-05-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.property'),
        ),
    ]
